# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoPlayInCellDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoPlayInCellDemo
  pod 'Moya', '~> 11.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ReachabilitySwift', '~> 4.1'

end
